server:
  port: 2020

liumapp:
  filemanager:
    savePath: /usr/local/tomcat/project/ocr-idcard/ocr-idcard-service/pic/
  ocr:
    ali:
      host: http://dm-51.data.aliyun.com
      path: /rest/160601/ocr/ocr_idcard.json
      appKey: 24931248
      appSecret: bed3a5c5712b01429fece22b37d930aa
      appCode: 4d16b6ab3fba4ada9dcac5c2ffe4da1a
      configure: face

